services:
  - type: web
    name: quatra-coffee
    env: python
    buildCommand: "./build.sh"
    build:
    usePoetry: false
    startCommand: "gunicorn quatra_coffee.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quatra_coffee.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: quatra-coffee.onrender.com
