services:
  - type: web
    name: quatra-coffee
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn quatra_coffee.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quatra_coffee.settings
      - key: SECRET_KEY
        value: d@j87tg@)@8o3+i%cuc#_0u!tpg0au9pi_wc4*=p4&ak&wno(z
      - key: ALLOWED_HOSTS
        value: quatra-coffee.onrender.com
